### ISSUE TITLE
是否支持新版的签名模式v2SigningEnabled？

### ISSUE THREAD

**Issue by haodynasty** [nukc/ApkMultiChannelPlugin#1]
如果使用美团方案是不是不支持新版签名模式？
如果使用的Android Gradle Plugin版本大于2.2.0，是否在signingConfigs 里增加 v2SigningEnabled false 禁用新版签名模式？

**Comment by haodynasty** [comment]
即是否能通过Android 7.0 APK Signature Scheme v2 验证...

**Comment by nukc** [comment]
这个插件不配合 gradle 使用，直接对 apk 文件进行多渠道打包。如果需要 v2 签名，配置的时候选择 apksigner 即可，具体可看 README

**Comment by nukc** [comment]
可以通过
