### ISSUE TITLE
是否后面考虑增加支持packer-ng-plugin的多渠道打包方案？

### ISSUE THREAD

**Issue by haodynasty** [nukc/ApkMultiChannelPlugin#2]
因为这个方案目前使用较多，https://github.com/mcxiaoke/packer-ng-plugin

**Comment by nukc** [comment]
有需求的话，会的

**Comment by haodynasty** [comment]
因为很多项目会使用wechat资源混淆https://github.com/shwenzhang/AndResGuard，里面特别提到了：渠道包的问题(**建议通过修改zip摘要的方式生产渠道包**)
在出渠道包的时候，解压重压缩会破坏7zip的效果

**Comment by nukc** [comment]
好的，多谢反馈

**Comment by nukc** [comment]
1.1版本已经支持 packer-ng-plugin 的多渠道打包方案；如果选中的 apk 是 v2 签名，多渠道打包后 channels 文件夹下的全部渠道 apk 都为 v1(jarsigner) 签名。具体可看 README。我已经测试过是可以打通整个流程的，可以读取到相应的渠道号，如果可以，希望你使用后回来这里进行反馈，谢谢。:)
