### ISSUE TITLE
使用该插件后packer-ng-plugin打包如何获取的channel为空？并且打包的名称如何统一修改

### ISSUE THREAD

**Issue by idisfkj** [nukc/ApkMultiChannelPlugin#4]

**Comment by idisfkj** [comment]
不使用该插件可以通过`PackerNg.getMarket(this);`获取`channel`，并且包名也能统一自定义。那么使用该插件要如何获取`channel`以至于能上传到友盟

**Comment by nukc** [comment]
README 里有说明，使用 packer-ng-plugin (即 write zip comment) 的方式，读取 channel: [ZipCommentHelper](https://gist.github.com/nukc/f762f73276c4ad02618147acd6978d16)，是在 ```PackerNg``` 基础上做了一点改动，用法一样。
