### ISSUE TITLE
用这种方式我怎么查看每个包的渠道？

### ISSUE THREAD

**Issue by Allen-cxl** [nukc/ApkMultiChannelPlugin#5]
用这种方式我怎么查看每个包的渠道？

**Comment by nukc** [comment]
可看每个 apk 的名字（包含渠道名）

**Comment by Allen-cxl** [comment]
渠道包打完后，每个渠道包的AndroidManifest UMENG_CHANNEL 这个会变吗？

**Comment by nukc** [comment]
buildType 是选择 update AndroidManifest.xml 的话，会的。
