### ISSUE TITLE
关于打包问题

### ISSUE THREAD

**Issue by jymot** [nukc/ApkMultiChannelPlugin#6]
您好，请教一下， 您的这中打包方式，是将已经签名(V2)的包修改渠道信息后，然后进行二次zipalign和签名，是么（针对V2签名的情况）？

**Comment by nukc** [comment]
在 README 有写 [Build Type 说明](https://github.com/nukc/ApkMultiChannelPlugin#build-type-说明)，看选择的是哪种方式。v2 的话都是最后再次签名
